      - name: Zip iFlow Folder
        run: |
          cd Email_to_pdf
          zip -r ../Email_to_pdf.zip .
          cd ..

      - name: Upload iFlow Package to SAP CPI
        run: |
          curl -X POST \
          "${{ secrets.CPI_URL }}/api/v1/IntegrationPackages('CPIPOC')/IntegrationDesigntimeArtifacts('Email_to_pdf')/$value
          -u "${{ secrets.CPI_USER }}:${{ secrets.CPI_PASS }}" \
          -H "Content-Type: application/zip" \
          --data-binary @Email_to_pdf.zip

      - name: Deploy iFlow to Runtime
        run: |
          curl -X POST \
          "${{ secrets.CPI_URL }}/api/v1/DeployIntegrationArtifact?artifactId=Email_to_pdf&version=1.0.0" \
          -u "${{ secrets.CPI_USER }}:${{ secrets.CPI_PASS }}"
